### ISSUE TITLE
Make runners respect 'DependsOn' attribute as test order tool

### ISSUE THREAD

**Issue by ummshsh** [Unicorn-TAF/taf-core#37]
# `DependsOn` as skip condition if previous test is failed
For now tests started in order of declaration.
`1 -> 2 -> 3`  

DependsOn works in this case and will skip tests if their predecessor is failed.

Lets say here `3` depends on `2`, then if `2` fails, `3` will be skipped as expected
```
1  2  3 
   ^  ^
   ^  Skipped
   Failed
```

**This case behaves as expected**

# `DependsOn` as test order tool
But if you declare some test to be depended on another one, but declare it in the wrong order, then it is not working as expected

If you were to declare tests in order
```
3  2  1
```
And add dependencies:
```
3 depends on 2
2 depends on 1
```

**Actual:** Tests will not be executed
**Expected:** Tests will be still executed with regard to dependency order

So proposal is to make `DependsOn` to be another ordering tool besides it's original function as skip condition

**Comment by dobriyanchik** [comment]
As of now:
 - `DependsOn` is already taken into account if `Random` tests execution mode is chosen (both `DependsOn` and `Order` attributes if to be more accurate)
 - In case of `Declaration` and `Alphabetical` ordering the proposal looks useless as essence of these two modes is a predefined tests order and they require dedicated efforts from authors to order the tests properly. 

So looks like the enhancement is not relevant now.
