### ISSUE TITLE
Misleading error message when comparing double with int

### ISSUE THREAD

**Issue by ummshsh** [Unicorn-TAF/taf-core#40]
![image](https://user-images.githubusercontent.com/14292399/218818475-010bcb3e-ac46-4a21-b66d-87f415320aef.png)
Or while comparing `(object){int}` with `int`

**Comment by dobriyanchik** [comment]
Looks like it's not an issue for now:
![image](https://github.com/user-attachments/assets/23c3d2c1-e86b-491f-b2f5-e944b6342b56)
